include:
  - ./docker/dnsmasq/docker-compose.yml
  - ./docker/horizon/docker-compose.yml
  - ./docker/hybridly/docker-compose.yml
  - ./docker/mailpit/docker-compose.yml
  - ./docker/minio/docker-compose.yml
  - ./docker/mysql/docker-compose.yml
  - ./docker/nginx/docker-compose.yml
  - ./docker/redis/docker-compose.yml
  - ./docker/traefik/docker-compose.yml

networks:
  laravel:
    name: project.${COMPOSE_PROJECT_NAME}
