api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          scheme: https
          to: https
  https:
    address: ":443"
  ping:
    address: ":8082"

global:
  sendAnonymousUsage: false

log:
  format: common
  level: info

ping:
  entryPoint: ping

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
