api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          scheme: https
          to: https
  https:
    address: ":443"

global:
  sendAnonymousUsage: false

log:
  format: common
  level: info

ping:
  entryPoint: traefik

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

tls:
  certificates:
    - certFile: /etc/traefik/certs/{{ env "COMPOSE_PROJECT_NAME" }}.cert
      keyFile: /etc/traefik/certs/{{ env "COMPOSE_PROJECT_NAME" }}.key
