##@ SSL Certificates

CERTIFICATES_DIRECTORY := $(DOCKER_DIRECTORY)/traefik/certs
CERTIFICATES_FILE := $(DOCKER_DIRECTORY)/traefik/config/dynamic/certificates.yml

.PHONY: update-certificates
update-certificates: ## Generate and update SSL certificates for the project.
	@echo "$(CYAN)[INFO]: Adding Certificate Authority to trust stores...$(RESET)"
	@if [ -f "$$(mkcert -CAROOT)/rootCA.pem" ]; then \
		echo "$(YELLOW)[WARNING]: Certificate Authority already added to trust stores.$(RESET)"; \
	else \
		mkcert -install; \
		echo "$(GREEN)[SUCCESS]: Certificate Authority added to trust stores.$(RESET)"; \
	fi
	@$(MAKE) generate-certificate name=$(PROJECT_NAME_SLUG)
	@$(MAKE) generate-certificate name=$(SHARED_PROJECT_NAME)
	@$(MAKE) list-certificates
	@echo "$(CYAN)[INFO]: Copying mkcert root CA...$(RESET)"
	@cp "$$(mkcert -CAROOT)/rootCA.pem" $(DOCKER_DIRECTORY)/hybridly/ssl/rootCA.pem
	@echo "$(GREEN)[SUCCESS]: mkcert root CA copied.$(RESET)"

.PHONY: generate-certificate
generate-certificate: ## Generate a wildcard certificate using 'make generate-certificate name=<name>' syntax.
ifndef name
	$(error Usage: make generate-certificate name=<name>)
endif
	@echo "$(CYAN)[INFO]: Updating SSL certificates for $(name).$(DNS_DOMAIN)...$(RESET)"
	@mkcert \
		-cert-file $(CERTIFICATES_DIRECTORY)/$(name).cert \
		-key-file $(CERTIFICATES_DIRECTORY)/$(name).key \
		"*.$(name).$(DNS_DOMAIN)" \
		"$(name).$(DNS_DOMAIN)" \
		127.0.0.1 0.0.0.0 > /dev/null 2>&1
	@echo "$(GREEN)[SUCCESS]: SSL certificates generated for $(name).$(DNS_DOMAIN).$(RESET)"

.PHONY: list-certificates
list-certificates: ## Rebuild the Traefik dynamic file listing every project certificate.
	@echo "$(CYAN)[INFO]: Listing certificates for Traefik...$(RESET)"
	@echo "# Generated by 'make update-certificates'. Do not edit by hand." > $(CERTIFICATES_FILE)
	@echo "tls:" >> $(CERTIFICATES_FILE)
	@echo "  certificates:" >> $(CERTIFICATES_FILE)
	@for certificate in $(CERTIFICATES_DIRECTORY)/*.cert; do \
		[ -e "$$certificate" ] || continue; \
		name=$$(basename "$$certificate" .cert); \
		echo "    - certFile: /etc/traefik/certs/$$name.cert" >> $(CERTIFICATES_FILE); \
		echo "      keyFile: /etc/traefik/certs/$$name.key" >> $(CERTIFICATES_FILE); \
	done
	@echo "$(GREEN)[SUCCESS]: Traefik certificate list updated.$(RESET)"
